
##Este procedimiento solo funciona p

- name: Copio el java 7 a usr local
  copy: src={{java_pack_7u65}} dest=/usr/local/src
  tags: java7

- name: Descomprimir 
  shell: tar -zxvf /usr/local/src/{{java_pack_7u65}} -C /usr/local
  tags: java7

- name: Hacer dueño a manduca
  shell: chown manduca.manduca -R {{java_home_7u65}}
  tags: java72
  ignore_errors: True

- name: Actualizar variables de ambiente en /etc/profile (para todos)
  shell: echo {{item}} >> /etc/profile
  with_items:
  - "###### SETEADOS AUTOMATICAMENTE CON ANSIBLE #######"
  - "export JAVA_HOME=/usr/local/jdk7"      
  - "export PATH=$PATH:/usr/local/jdk7/bin"
  tags: env

- name: Link symbolico java 7
  file: src={{java_home_7u65}} dest={{main_app_home}}/jdk7 state=link
  tags: links
  ignore_errors: True
  # owner=manduca group=manduca state=link