
# Ansible que instala la guia de servicios
# Requiere ip con acceso a 204.228.236.7:6200 <-cable
# Requiere ant
# http://204.13.51.76/GS/2014-06-15    -> ejemplo para verificar que funcione, debe traer un json con data


- name: asegurar que {{local2}} exists
  file: path="{{local2}}"   state=directory
  tags: cvs

- name:  CVS Loguin {{DEUMovil}}
  shell: cvs -d :pserver:manduca:D3c4r#m6o!A@{{cvs_ip}}:/home/cvs/commons/ login
  sudo: yes
  sudo_user: manduca    
  tags:  cvs

- name:  Checkout del proyecto  {{DEUMovil}}
  command: chdir={{local2}} cvs -d :pserver:manduca@{{cvs_ip}}:/home/cvs/commons checkout {{DEUMovil}}
  sudo: yes
  sudo_user: manduca    
  tags: cvs

- name: Reemplazar buildproperties con el template {{DEUMovil}}
  template:
    src=build.properties.j2
    dest="{{local2}}/{{DEUMovil}}/build.properties"
  sudo: yes
  sudo_user: manduca    
  tags: deuM

- name:  run ant build {{DEUMovil}}
  shell: chdir={{local2}}/{{DEUMovil}} export _JAVA_OPTIONS="-XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC" && export LC_ALL=es_VE.ISO8859-1 && ant compila && ant portal
  sudo: yes
  sudo_user: manduca
  environment: manduca_env
  tags: deuM



