
##Este procedimiento solo funciona para java 6 los demas con descomprimir basta

- name: Copio el java 6 a usr local
  copy: src={{java_pack_6u45}} dest=/usr/local

- name: hay que hacerlo ejecutable
  shell: chmod +x /usr/local/{{java_pack_6u45}} 

- name: ejecutar el binario  
  shell: chdir=/usr/local echo -e 'y\ny\n\n' | ./{{java_pack_6u45}} 

- name: Hacer dueño a manduca
  shell: chown manduca.manduca -R {{java_home_6u45}}