
# Ansible que instala Admin del el Universal
# Wuelfhis Asuaje 
# Infraestructura de Sistemas
 
- name: asegurar que {{local2}}/scripts exists
  file: path="{{local2}}/scripts"   state=directory owner=manduca group=manduca recurse=yes
  tags: scripts

- name: Copio resinAdmin.conf {{Admin}}
  shell: cp /local2/applications/poll/conf/resinAdmin.conf  {{local2}}/scripts/
  sudo: yes
  sudo_user: manduca 
  tags: copy

- name: Copio admin.sh {{Admin}}
  shell: cp /local2/applications/poll/conf/admin.sh  {{local2}}/scripts/
  sudo: yes
  sudo_user: manduca 
  tags: copy

- name: start admin.sh {{Admin}}
  shell: chdir={{local2}}/scripts chmod +x admin.sh && ./admin.sh start
  sudo: yes
  sudo_user: manduca 
  environment: manduca_env
  tags: startadmin