
# Ansible que instala la guia de servicios
# Requiere ip con acceso a 204.228.236.7:6200 <-cable
# Requiere ant
# http://204.13.51.76/GS/2014-06-15    -> ejemplo para verificar que funcione, debe traer un json con data

- name: download ANT
  action: get_url
      url="{{ant_download_url}}"
      dest="/usr/local/src"
  tags: ant

- name: unpacks ANT
  shell: tar -zxvf /usr/local/src/apache-ant-1.9.4-bin.tar.gz -C /usr/local
  tags: ant

- name:  CVS Loguin
  shell: cvs -d :pserver:cvsuser:cvsuser@{{cvs_ip}}:/home/cvs/guiaservicios login
  tags:  cvs

- name: asegurar que {{main_app_home}} exists
  file: path="{{main_app_home}}"   state=directory
  tags: cvs

- name:  Checkout del proyecto guia de servicios
  command: chdir={{main_app_home}} cvs -d :pserver:cvsuser:cvsuser@{{cvs_ip}}:/home/cvs/ co guiaservicios
  tags: cvs

- name: Reemplazar ant.sh con el template
  template:
    src=ant.sh.j2
    dest="{{main_app_home}}/guiaservicios/guiaservicioWebPublic/script/ant.sh"
  tags: gs

- name:  run ant build
  command: chdir={{main_app_home}}/guiaservicios/guiaservicioWebPublic/script/ /bin/bash ant.sh package
  tags: gs

- name:  run ant build
  command: chdir={{main_app_home}}/guiaservicios/guiaservicioWebPublic/script/ /bin/bash ant.sh createWebapp
  tags: gs


