
##Este procedimiento solo funciona para java 5 los demas con descomprimir basta

- name: Copio el java 5 a usr local
  copy: src={{java_pack_5}} dest={{main_app_home}}
  tags: java5

- name: hay que hacerlo ejecutable
  shell: chmod +x {{main_app_home}}/{{java_pack_5}} 
  tags: java5

- name: ejecutar el binario
  shell: chdir={{main_app_home}} echo -e 'yes\n' | ./{{java_pack_5}}
  tags: java5

- name: Hacer dueño a manduca
  shell: chown manduca.manduca -R {{java_home_5}}
  tags: java5