#variables para la instalacion de openresty


# variables para instalacion Geoip


geoip_pack_latest: 'GeoIP-latest.tar.gz'
geoip_dir: "/usr/local/src/"
geoip_pack_city: "GeoLiteCity.dat.gz"
geoip_pack_data: "GeoIP.dat.gz"


#dowload modulos openresty
#openresty_modulo_dowload_stream: "https://github.com/wandenberg/nginx-push-stream-module.git"
#openresty_modulo_dowload_http: "https://github.com/yaoweibin/ngx_http_substitutions_filter_module.git"
openresty_modulo_pack_hash: "ngx_http_consistent_hash-master.zip"
openresty_modulo_dowload_http: "ngx_http_substitutions_filter_module-master.zip"
openresty_modulo_dowload_stream: "nginx-push-stream-module-master.zip"

#download openresty 

openresty_pack_latest: "ngx_openresty-1.7.7.1.tar.gz"
openresty_dir: "/usr/local/src"
openresty_compile: "--add-module=/usr/local/src/nginx-push-stream-module-master/ \ 
   --add-module=/usr/local/src/ngx_http_consistent_hash-master/ \ 
   --add-module=/usr/local/src/ngx_http_substitutions_filter_module-master/ \
   --error-log-path=/usr/local/nginx/logs/error.log \
   --group=nobody \
   --http-client-body-temp-path=/var/tmp/nginx/client/ \
   --http-log-path=/usr/local/nginx/logs/access.log \
   --http-proxy-temp-path=/var/tmp/nginx/proxy/ \
   --lock-path=/var/lock/nginx \
   --pid-path=/var/run/nginx.pid \
   --prefix=/usr/local/ \
   --sbin-path=/usr/local/bin/ \
   --user=nobody \
   --with-http_geoip_module \
   --with-http_realip_module \
   --with-http_ssl_module \
   --with-http_stub_status_module \
   --without-http_autoindex_module \
   --without-http_browser_module \
   --without-http_fastcgi_module \
   --without-http_limit_conn_module \
   --without-http_limit_req_module \
   --without-http_memcached_module \
   --without-http_scgi_module \
   --without-http_split_clients_module \
   --without-http_upstream_ip_hash_module \
   --without-http_upstream_least_conn_module \
   --without-http_userid_module \
   --without-http_uwsgi_module \
   --without-mail_imap_module \
   --without-mail_pop3_module \
   --without-mail_smtp_module"

   #archivo de configuracion:

nginxconf: "nginx.conf"
nginxconfruta: "/usr/local/nginx/conf/"

   #archivo mime.types de carpeta compones.

mime: "mime.types"
mimeruta: "/usr/local/nginx/conf/components/"